# Generated by Django 4.0.10 on 2025-02-13 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_added_by_alter_user_deleted_by_and_more'),
        ('attendance', '0003_alter_attendance_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_added_by', to='users.user'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_deleted_by', to='users.user'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to='users.user'),
        ),
    ]
