# Generated by Django 4.0.10 on 2025-02-13 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_alter_department_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_added_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
