# Generated by Django 4.0.10 on 2025-02-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_added_by_alter_user_deleted_by_and_more'),
        ('role', '0004_alter_role_added_by_alter_role_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
